import ReactQueryWrapper from "./components/ReactQueryWrapper";
import SessionProviderWrapper from "./components/SessionProviderWrapper";
import Navigation from "./components/navigation/Navigation";
import "./globals.css";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " min-h-screen"}>
        <SessionProviderWrapper>
          <ReactQueryWrapper>
            <Navigation />
            {children}
          </ReactQueryWrapper>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
